name: Firebase for pipelines
description: This action allows you to deploy a firebase function

inputs:
  firebase-token:
    description: Token generated to authenticate in firebase
    required: true
  resources-name:
    description: Name of the folder containing the resources to be deployed
    required: true
  project-name:
    description: Firebase project name
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy a firebase function
      shell: bash
      run: |
        CURRENT_PATH=$(pwd)/.github/actions/pipelines-firebase-functions
        bash $CURRENT_PATH/deploy-function.sh \
          --firebase-token=${{ inputs.firebase-token }} \
          --resources-name=${{ inputs.resources-name }} \
          --project-name=${{ inputs.project-name }}